version: "3"

services:
    db:
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - rexit-test-task
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/html
        networks:
            - rexit-test-task
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/html
        ports:
            - 8080:80
        networks:
            - rexit-test-task
        env_file:
            - .env.nginx.local

volumes:

    db_app:

networks:
    rexit-test-task:
